package Models;
// Generated Mar 17, 2016 1:00:28 PM by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.core.JsonParseException;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.io.IOException;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;




/**
 * Article generated by hbm2java
 */
@Entity
@Table(name = "Article")
public class Article  implements java.io.Serializable {

     @Id @GeneratedValue
     @Column(name = "ARTICLE_ID")
     private int id;
     
     @Column(name = "ARTICLE_DESCRIPTION")
     private String description;
     
     @Column(name = "ARTICLE_STOCK")
     private Integer stock;
     
     @OneToOne
     @JoinColumn(name="TYPE_INVENTORY_ID")
     private TypeInventory typeInventory;
     
     @Column(name = "ARTICLE_UNITPRICE")
     private Float unitPrice;
     
     @Column(name = "ARTICLE_STATE")
     private Byte state;

    public Article() {
    }

    public Article(int id) {
        this.id = id;
    }
    public Article(int id, String description, Integer stock, Float unitPrice, Byte state) {
       this.id = id;
       this.description = description;
       this.stock = stock;
       this.unitPrice = unitPrice;
       this.state = state;
    }
    
    @JsonCreator
    public static Article Create(String jsonString) throws JsonParseException, JsonMappingException, IOException {
        ObjectMapper mapper = new ObjectMapper();
        Article module = null;
        module = mapper.readValue(jsonString, Article.class);
        return module;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Integer getStock() {
        return this.stock;
    }
    
    public void setStock(Integer stock) {
        this.stock = stock;
    }
    public TypeInventory getTypeInventory() {
        return this.typeInventory;
    }
    
    public void setTypeInventory(TypeInventory typeInventory) {
        this.typeInventory = typeInventory;
    }
    public Float getUnitPrice() {
        return this.unitPrice;
    }
    
    public void setUnitPrice(Float unitPrice) {
        this.unitPrice = unitPrice;
    }
    public Byte getState() {
        return this.state;
    }
    
    public void setState(Byte state) {
        this.state = state;
    }




}


