package Models;
// Generated Mar 17, 2016 1:00:28 PM by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.core.JsonParseException;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.io.IOException;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Transaction generated by hbm2java
 */
@Entity
@Table(name = "Transaction")
public class Transaction  implements java.io.Serializable {


     @Id @GeneratedValue(strategy=GenerationType.IDENTITY)
     @Column(name = "TRANSACTION_ID")
     private int id;
     
     @OneToOne
     @JoinColumn(name="TYPE_TRANSACTION_ID")
     private TransactionType type;
     
     @OneToOne
     @JoinColumn(name="ARTICLE_ID")
     private Article idArticle;
     
     @Column(name = "TRANSACTION_DATE")
     private Date date;
     
     @Column(name = "TRANSACTION_AMOUNT")
     private Integer amount;
     
     @Column(name = "TRANSACTION_COST")
     private Float cost;

    public Transaction() {
    }

	
    public Transaction(int id) {
        this.id = id;
    }
    public Transaction(int id, String type, Date date, Integer amount, Float cost) {
       this.id = id;
       this.date = date;
       this.amount = amount;
       this.cost = cost;
    }
    
    @JsonCreator
    public static Transaction Create(String jsonString) throws JsonParseException, JsonMappingException, IOException {
        ObjectMapper mapper = new ObjectMapper();
        Transaction module = null;
        module = mapper.readValue(jsonString, Transaction.class);
        return module;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public TransactionType getType() {
        return this.type;
    }
    
    public void setType(TransactionType type) {
        this.type = type;
    }
    public Article getIdArticle() {
        return this.idArticle;
    }
    
    public void setIdArticle(Article idArticle) {
        this.idArticle = idArticle;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Integer getAmount() {
        return this.amount;
    }
    
    public void setAmount(Integer amount) {
        this.amount = amount;
    }
    public Float getCost() {
        return this.cost;
    }
    
    public void setCost(Float cost) {
        this.cost = cost;
    }




}


