package Models;
// Generated Mar 17, 2016 1:00:28 PM by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.core.JsonParseException;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.io.IOException;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;




/**
 * TypeInventory generated by hbm2java
 */
@Entity
@Table(name = "TypeInventory")
public class TypeInventory  implements java.io.Serializable {

     @Id @GeneratedValue
     @Column(name = "TYPE_INVENTORY_ID")
     private int id;
     
     @Column(name = "TYPE_INVENTORY_DESCRIPTION")
     private String description;
     
     @Column(name = "TYPE_INVENTORY_ACCOUNT")
     private Integer account;
     
     @Column(name = "TYPE_INVENTORY_STATE")
     private Byte state;

    public TypeInventory() {
    }

	
    public TypeInventory(int id) {
        this.id = id;
    }
    
    public TypeInventory(int id, String description, Integer account, Byte state) {
       this.id = id;
       this.description = description;
       this.account = account;
       this.state = state;
    }
    
    @JsonCreator
    public static TypeInventory Create(String jsonString) throws JsonParseException, JsonMappingException, IOException {
        ObjectMapper mapper = new ObjectMapper();
        TypeInventory module = null;
        module = mapper.readValue(jsonString, TypeInventory.class);
        return module;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Integer getAccount() {
        return this.account;
    }
    
    public void setAccount(Integer account) {
        this.account = account;
    }
    public Byte getState() {
        return this.state;
    }
    
    public void setState(Byte state) {
        this.state = state;
    }




}


