package Models;
// Generated Mar 17, 2016 1:00:28 PM by Hibernate Tools 4.3.1



/**
 * Warehouse generated by hbm2java
 */
public class Warehouse  implements java.io.Serializable {


     private int id;
     private String description;
     private Byte state;

    public Warehouse() {
    }

	
    public Warehouse(int id) {
        this.id = id;
    }
    public Warehouse(int id, String description, Byte state) {
       this.id = id;
       this.description = description;
       this.state = state;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Byte getState() {
        return this.state;
    }
    
    public void setState(Byte state) {
        this.state = state;
    }




}


